#
# ActiveRecord::Turntable configuration file
#
barrage_default: &barrage_default
  seq_type: barrage
  options:
    generators:
      - name: msec
        length: 39 # MAX 17.4 years from start_at
        start_at: 1396278000000 # 2014/04/01 00:00:00 JST
      - name: redis_worker_id
        length: 16
        ttl: 300
        redis:
          host: '127.0.0.1'
      - name: sequence
        length: 9

development:
  clusters:
    user_cluster:
      algorithm: range_bsearch
      seq:
        user_seq:
          seq_type: mysql
          connection: user_seq_1
      shards:
        - connection: user_shard_1
          less_than: 10
        - connection: user_shard_2
          less_than: 20
        - connection: user_shard_3
          less_than: 30
        - connection: user_shard_1
          less_than: 10000

test:
  clusters:
    user_cluster:
      algorithm: range_bsearch
      seq:
        user_seq:
          seq_type: mysql
          connection: user_seq_1
      shards:
        - connection: user_shard_1
          less_than: 20000
        - connection: user_shard_2
          less_than: 40000
        - connection: user_shard_3
          less_than: 10000000

production:
  clusters:
    user_cluster:
      algorithm: range_bsearch
      seq:
        user_seq:
          seq_type: mysql
          connection: user_seq_1
      shards:
        - connection: user_shard_1
          less_than: 20000
        - connection: user_shard_2
          less_than: 40000
        - connection: user_shard_3
          less_than: 10000000
